version: "3"
services:
  database:
    image: postgres:13.11
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=db_pass
      - POSTGRES_USER=db_user
      - POSTGRES_DB=movie_database_db
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
  backend:
    build: ./backend
    ports:
      - 8000:3001
